name: Bazel Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Verify Go
      run: |
        go version
        go env
        
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.15.0
      with:
        # Avoid downloading Bazel every time.
        bazelisk-cache: true
        # Store build cache per workflow.
        disk-cache: ${{ github.workflow }}
        # Share repository cache between workflows.
        repository-cache: true
      
    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        ffmpeg -version
        
    - name: Install MinIO
      run: |
        # Download latest MinIO binary
        echo "Downloading MinIO..."
        curl -L https://dl.min.io/server/minio/release/linux-amd64/minio -o /tmp/minio
        echo "Installing MinIO..."
        sudo mv /tmp/minio /usr/local/bin/minio
        sudo chmod +x /usr/local/bin/minio
        echo "Verifying MinIO installation..."
        minio --version
        echo "MinIO installation complete"
        
    - name: Install Google Cloud SDK
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
        sudo apt-get update
        sudo apt-get install -y google-cloud-cli
        gcloud --version
        
    - name: Cache Bazel
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/bazel
          ~/.cache/bazelisk
        key: ${{ runner.os }}-bazel-${{ hashFiles('**/MODULE.bazel', '**/MODULE.bazel.lock') }}
        restore-keys: |
          ${{ runner.os }}-bazel-
          
    - name: Verify Bazel Setup
      run: |
        bazelisk version
        bazelisk info
        
    - name: List Available Targets
      run: |
        echo "=== Available Targets ==="
        bazelisk query //... --output=label_kind
        
    - name: Run Bazel Tests
      run: |
        bazelisk test //...
        
    - name: Build All Targets
      run: |
        bazelisk build //...
        
    - name: Show Test Results
      if: always()
      run: |
        echo "=== Test Results ==="
        find bazel-testlogs -name "test.log" -exec echo "=== {} ===" \; -exec cat {} \;
        
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          bazel-testlogs/
          bazel-out/
        retention-days: 7